@echo off

echo 正在编译RCServer.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in RCServer.au3 /out .\release\RCServer.exe /comp 4
echo 正在编译email2.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\email2.au3 /out .\release\utils\email2.exe /comp 4
echo 正在编译email.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\email.au3 /out .\release\utils\email.exe /comp 4
echo 正在编译explorer.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\explorer.au3 /out .\release\utils\explorer.exe /comp 4
echo 正在编译mstsc.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\mstsc.au3 /out .\release\utils\mstsc.exe /comp 4
echo 正在编译show.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\show.au3 /out .\release\utils\show.exe /comp 4
echo 正在编译viewlog.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\viewlog.au3 /out .\release\utils\viewlog.exe /comp 4
echo 正在编译run.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\run.au3 /out .\release\utils\run.exe /comp 4
echo 正在编译kill.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\kill.au3 /out .\release\utils\kill.exe /comp 4
echo 正在编译echo.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\echo.au3 /out .\release\utils\echo.exe /comp 4
echo 正在编译 打开远程控制.au3...
"E:\Program Files"\AutoIt3\Aut2Exe\Aut2exe.exe /in .\utils\echo.au3 /out .\release\utils\打开远程控制.exe /comp 4
echo 编译完毕...

xcopy /E/Y helper .\release\helper\

echo 拷贝版本成功，任意键退出...
pause

