#include-once


;no back slash ends with the path
Global $regBase = "HKEY_LOCAL_MACHINE\SOFTWARE\CHX\AutoChecking"

Global $REG_MESSAGE_KEY = "message"
Global $MESSAGE_SHOW_TASK_INFO = "MESSAGE_SHOW_TASK_INFO"
Global $MESSAGE_TERMINATE = "MESSAGE_TERMINATE"
Global $MESSAGE_SHOW_CURRENT_TIMER = "MESSAGE_SHOW_CURRENT_TIMER"
Global $MESSAGE_RELOAD_TIMER = "MESSAGE_RELOAD_TIMER"
Global $MESSAGE_IMMEDIATE_CHECK = "MESSAGE_IMMEDIATE_CHECK"
Global $MESSAGE_IMMEDIATE_CHECK_TEST = "MESSAGE_IMMEDIATE_CHECK_TEST"
Global $MESSAGE_RELOAD_CONF = "MESSAGE_RELOAD_CONF"
Global $REG_MESSAGES[8] = [7, _
		$MESSAGE_SHOW_TASK_INFO, _
		$MESSAGE_TERMINATE, _
		$MESSAGE_SHOW_CURRENT_TIMER, _
		$MESSAGE_RELOAD_TIMER, _
		$MESSAGE_IMMEDIATE_CHECK, _
		$MESSAGE_IMMEDIATE_CHECK_TEST, _
		$MESSAGE_RELOAD_CONF ]
